In [11]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [12]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [13]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [14]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [15]:
X=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df['needs_water']

In [16]:

X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [17]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [18]:

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [20]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [22]:
model.compile(optimizer="sgd",loss = "binary_crossentropy",metrics=["accuracy"])

In [24]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,
    batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.6416 - val_accuracy: 0.7500 - val_loss: 0.6688
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.6333 - val_accuracy: 0.7500 - val_loss: 0.6686
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6250 - val_accuracy: 0.7500 - val_loss: 0.6683
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6441 - val_accuracy: 0.7500 - val_loss: 0.6681
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9583 - loss: 0.6221 - val_accuracy: 0.7500 - val_loss: 0.6679
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.6272 - val_accuracy: 0.7500 - val_loss: 0.6676
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.6207 - val_accuracy: 0.7500 - val_loss: 0.6674
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6328 - val_accuracy: 0.7500 - val_loss: 0.6671
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9271 - loss: 0.6260 - val_accuracy: 0.7500 - val_loss: 0.6668
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6376 - val_accuracy: 0.7500 - val_loss: 0.6665
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.6193 - val_accuracy: 0.7500 - val_loss: 0.6662
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6292 - val_accuracy: 0.7500 - val_loss: 0.6659
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.6360 - val_accuracy: 0.7500 - val_loss: 0.6656
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6343 - val_accuracy: 0.7500 - val_loss: 0.6653
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.6310 - val_accuracy: 0.7500 - val_loss: 0.6650
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9583 - loss: 0.6183 - val_accuracy: 0.7500 - val_loss: 0.6647
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9583 - loss: 0.6087 - val_accuracy: 0.7500 - val_loss: 0.6643
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6240 - val_accuracy: 0.7500 - val_loss: 0.6640
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6388 - val_accuracy: 0.7500 - val_loss: 0.6637
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6314 - val_accuracy: 0.7500 - val_loss: 0.6634
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6282 - val_accuracy: 0.7500 - val_loss: 0.6630
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.6210 - val_accuracy: 0.7500 - val_loss: 0.6627
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9583 - loss: 0.6211 - val_accuracy: 0.7500 - val_loss: 0.6624
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.6228 - val_accuracy: 0.7500 - val_loss: 0.6621
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6160 - val_accuracy: 0.7500 - val_loss: 0.6618
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.6278 - val_accuracy: 0.7500 - val_loss: 0.6614
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6206 - val_accuracy: 0.7500 - val_loss: 0.6611
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6247 - val_accuracy: 0.7500 - val_loss: 0.6608
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6264 - val_accuracy: 0.7500 - val_loss: 0.6605
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6251 - val_accuracy: 0.7500 - val_loss: 0.6602
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6228 - val_accuracy: 0.7500 - val_loss: 0.6599
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6183 - val_accuracy: 0.7500 - val_loss: 0.6596
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6138 - val_accuracy: 0.7500 - val_loss: 0.6593
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6213 - val_accuracy: 0.7500 - val_loss: 0.6588
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6030 - val_accuracy: 0.7500 - val_loss: 0.6585
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.6171 - val_accuracy: 0.7500 - val_loss: 0.6581
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6307 - val_accuracy: 0.7500 - val_loss: 0.6577
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.6215 - val_accuracy: 0.7500 - val_loss: 0.6573
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.6111 - val_accuracy: 0.7500 - val_loss: 0.6570
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9583 - loss: 0.6059 - val_accuracy: 0.7500 - val_loss: 0.6566
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6238 - val_accuracy: 0.7500 - val_loss: 0.6562
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6182 - val_accuracy: 0.7500 - val_loss: 0.6559
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5943 - val_accuracy: 0.7500 - val_loss: 0.6555
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6249 - val_accuracy: 0.7500 - val_loss: 0.6552
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9583 - loss: 0.6147 - val_accuracy: 0.7500 - val_loss: 0.6548
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6240 - val_accuracy: 0.7500 - val_loss: 0.6544
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5924 - val_accuracy: 0.7500 - val_loss: 0.6541
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6200 - val_accuracy: 0.7500 - val_loss: 0.6537
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.6056 - val_accuracy: 0.7500 - val_loss: 0.6533
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6230 - val_accuracy: 0.7500 - val_loss: 0.6530
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5977 - val_accuracy: 0.7500 - val_loss: 0.6526
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6173 - val_accuracy: 0.7500 - val_loss: 0.6522
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6058 - val_accuracy: 0.7500 - val_loss: 0.6519
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6054 - val_accuracy: 0.7500 - val_loss: 0.6515
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6193 - val_accuracy: 0.7500 - val_loss: 0.6511
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6122 - val_accuracy: 0.7500 - val_loss: 0.6507
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6116 - val_accuracy: 0.7500 - val_loss: 0.6504
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6094 - val_accuracy: 0.7500 - val_loss: 0.6499
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.6232 - val_accuracy: 0.7500 - val_loss: 0.6495
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6084 - val_accuracy: 0.7500 - val_loss: 0.6492
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6049 - val_accuracy: 0.7500 - val_loss: 0.6488
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.6159 - val_accuracy: 0.7500 - val_loss: 0.6483
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6117 - val_accuracy: 0.7500 - val_loss: 0.6479
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.6230 - val_accuracy: 0.7500 - val_loss: 0.6475
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6181 - val_accuracy: 0.7500 - val_loss: 0.6472
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6041 - val_accuracy: 0.7500 - val_loss: 0.6468
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.6205 - val_accuracy: 0.7500 - val_loss: 0.6464
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5918 - val_accuracy: 0.7500 - val_loss: 0.6460
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.6110 - val_accuracy: 0.7500 - val_loss: 0.6456
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6159 - val_accuracy: 0.7500 - val_loss: 0.6451
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6121 - val_accuracy: 0.7500 - val_loss: 0.6447
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.6088 - val_accuracy: 0.7500 - val_loss: 0.6443
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5873 - val_accuracy: 0.7500 - val_loss: 0.6438
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6134 - val_accuracy: 0.7500 - val_loss: 0.6434
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5959 - val_accuracy: 0.7500 - val_loss: 0.6430
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.6068 - val_accuracy: 0.7500 - val_loss: 0.6426
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.5909 - val_accuracy: 0.7500 - val_loss: 0.6422
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6055 - val_accuracy: 0.7500 - val_loss: 0.6418
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5907 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6092 - val_accuracy: 0.7500 - val_loss: 0.6409
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.6010 - val_accuracy: 0.7500 - val_loss: 0.6405
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 1.0000 - loss: 0.5970 - val_accuracy: 0.7500 - val_loss: 0.6400
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5890 - val_accuracy: 0.7500 - val_loss: 0.6396
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.5978 - val_accuracy: 0.7500 - val_loss: 0.6392
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.6123 - val_accuracy: 0.7500 - val_loss: 0.6388
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 1.0000 - loss: 0.5959 - val_accuracy: 1.0000 - val_loss: 0.6383
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 1.0000 - loss: 0.5878 - val_accuracy: 1.0000 - val_loss: 0.6378
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5958 - val_accuracy: 1.0000 - val_loss: 0.6374
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5976 - val_accuracy: 1.0000 - val_loss: 0.6370
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5784 - val_accuracy: 1.0000 - val_loss: 0.6365
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5850 - val_accuracy: 1.0000 - val_loss: 0.6361
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5966 - val_accuracy: 1.0000 - val_loss: 0.6357
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.5797 - val_accuracy: 1.0000 - val_loss: 0.6352
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 1.0000 - loss: 0.6081 - val_accuracy: 1.0000 - val_loss: 0.6348
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5913 - val_accuracy: 1.0000 - val_loss: 0.6344
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.5836 - val_accuracy: 1.0000 - val_loss: 0.6339
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 1.0000 - loss: 0.5798 - val_accuracy: 1.0000 - val_loss: 0.6335
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.5880 - val_accuracy: 1.0000 - val_loss: 0.6331
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.5917 - val_accuracy: 1.0000 - val_loss: 0.6326
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 1.0000 - loss: 0.6078 - val_accuracy: 1.0000 - val_loss: 0.6322